/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedDashboardImport } from './routes/_protected/_dashboard'
import { Route as ProtectedDashboardStudentStudentImport } from './routes/_protected/_dashboard/student/_student'
import { Route as ProtectedDashboardInstructorInstructorImport } from './routes/_protected/_dashboard/instructor/_instructor'
import { Route as ProtectedDashboardAdminAdminImport } from './routes/_protected/_dashboard/admin/_admin'
import { Route as ProtectedDashboardStudentStudentIndexImport } from './routes/_protected/_dashboard/student/_student/index'
import { Route as ProtectedDashboardListTeachersIndexImport } from './routes/_protected/_dashboard/list/teachers/index'
import { Route as ProtectedDashboardListSubjectsIndexImport } from './routes/_protected/_dashboard/list/subjects/index'
import { Route as ProtectedDashboardListStudentsIndexImport } from './routes/_protected/_dashboard/list/students/index'
import { Route as ProtectedDashboardListResultsIndexImport } from './routes/_protected/_dashboard/list/results/index'
import { Route as ProtectedDashboardListLessonsIndexImport } from './routes/_protected/_dashboard/list/lessons/index'
import { Route as ProtectedDashboardListExamsIndexImport } from './routes/_protected/_dashboard/list/exams/index'
import { Route as ProtectedDashboardListEventsIndexImport } from './routes/_protected/_dashboard/list/events/index'
import { Route as ProtectedDashboardListClassesIndexImport } from './routes/_protected/_dashboard/list/classes/index'
import { Route as ProtectedDashboardListAssignmentsIndexImport } from './routes/_protected/_dashboard/list/assignments/index'
import { Route as ProtectedDashboardListAnnouncementsIndexImport } from './routes/_protected/_dashboard/list/announcements/index'
import { Route as ProtectedDashboardInstructorInstructorIndexImport } from './routes/_protected/_dashboard/instructor/_instructor/index'
import { Route as ProtectedDashboardAdminAdminIndexImport } from './routes/_protected/_dashboard/admin/_admin/index'
import { Route as ProtectedDashboardListTeachersIdImport } from './routes/_protected/_dashboard/list/teachers/$id'
import { Route as ProtectedDashboardListStudentsIdImport } from './routes/_protected/_dashboard/list/students/$id'
import { Route as ProtectedDashboardInstructorInstructorCoursesImport } from './routes/_protected/_dashboard/instructor/_instructor/courses'
import { Route as ProtectedDashboardInstructorInstructorAnalyticsImport } from './routes/_protected/_dashboard/instructor/_instructor/analytics'

// Create Virtual Routes

const ProtectedDashboardStudentImport = createFileRoute(
  '/_protected/_dashboard/student',
)()
const ProtectedDashboardInstructorImport = createFileRoute(
  '/_protected/_dashboard/instructor',
)()
const ProtectedDashboardAdminImport = createFileRoute(
  '/_protected/_dashboard/admin',
)()
const ProtectedDashboardAnnouncementsLazyImport = createFileRoute(
  '/_protected/_dashboard/announcements',
)()

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedDashboardStudentRoute = ProtectedDashboardStudentImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)

const ProtectedDashboardInstructorRoute =
  ProtectedDashboardInstructorImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardAdminRoute = ProtectedDashboardAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)

const ProtectedDashboardAnnouncementsLazyRoute =
  ProtectedDashboardAnnouncementsLazyImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_protected/_dashboard/announcements.lazy').then(
      (d) => d.Route,
    ),
  )

const ProtectedDashboardStudentStudentRoute =
  ProtectedDashboardStudentStudentImport.update({
    id: '/_student',
    getParentRoute: () => ProtectedDashboardStudentRoute,
  } as any)

const ProtectedDashboardInstructorInstructorRoute =
  ProtectedDashboardInstructorInstructorImport.update({
    id: '/_instructor',
    getParentRoute: () => ProtectedDashboardInstructorRoute,
  } as any)

const ProtectedDashboardAdminAdminRoute =
  ProtectedDashboardAdminAdminImport.update({
    id: '/_admin',
    getParentRoute: () => ProtectedDashboardAdminRoute,
  } as any)

const ProtectedDashboardStudentStudentIndexRoute =
  ProtectedDashboardStudentStudentIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardStudentStudentRoute,
  } as any)

const ProtectedDashboardListTeachersIndexRoute =
  ProtectedDashboardListTeachersIndexImport.update({
    id: '/list/teachers/',
    path: '/list/teachers/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListSubjectsIndexRoute =
  ProtectedDashboardListSubjectsIndexImport.update({
    id: '/list/subjects/',
    path: '/list/subjects/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListStudentsIndexRoute =
  ProtectedDashboardListStudentsIndexImport.update({
    id: '/list/students/',
    path: '/list/students/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListResultsIndexRoute =
  ProtectedDashboardListResultsIndexImport.update({
    id: '/list/results/',
    path: '/list/results/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListLessonsIndexRoute =
  ProtectedDashboardListLessonsIndexImport.update({
    id: '/list/lessons/',
    path: '/list/lessons/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListExamsIndexRoute =
  ProtectedDashboardListExamsIndexImport.update({
    id: '/list/exams/',
    path: '/list/exams/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListEventsIndexRoute =
  ProtectedDashboardListEventsIndexImport.update({
    id: '/list/events/',
    path: '/list/events/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListClassesIndexRoute =
  ProtectedDashboardListClassesIndexImport.update({
    id: '/list/classes/',
    path: '/list/classes/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListAssignmentsIndexRoute =
  ProtectedDashboardListAssignmentsIndexImport.update({
    id: '/list/assignments/',
    path: '/list/assignments/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListAnnouncementsIndexRoute =
  ProtectedDashboardListAnnouncementsIndexImport.update({
    id: '/list/announcements/',
    path: '/list/announcements/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardInstructorInstructorIndexRoute =
  ProtectedDashboardInstructorInstructorIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardInstructorInstructorRoute,
  } as any)

const ProtectedDashboardAdminAdminIndexRoute =
  ProtectedDashboardAdminAdminIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardListTeachersIdRoute =
  ProtectedDashboardListTeachersIdImport.update({
    id: '/list/teachers/$id',
    path: '/list/teachers/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardListStudentsIdRoute =
  ProtectedDashboardListStudentsIdImport.update({
    id: '/list/students/$id',
    path: '/list/students/$id',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardInstructorInstructorCoursesRoute =
  ProtectedDashboardInstructorInstructorCoursesImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => ProtectedDashboardInstructorInstructorRoute,
  } as any)

const ProtectedDashboardInstructorInstructorAnalyticsRoute =
  ProtectedDashboardInstructorInstructorAnalyticsImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProtectedDashboardInstructorInstructorRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboard': {
      id: '/_protected/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/_dashboard/announcements': {
      id: '/_protected/_dashboard/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof ProtectedDashboardAnnouncementsLazyImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/admin': {
      id: '/_protected/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedDashboardAdminImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/admin/_admin': {
      id: '/_protected/_dashboard/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminImport
      parentRoute: typeof ProtectedDashboardAdminRoute
    }
    '/_protected/_dashboard/instructor': {
      id: '/_protected/_dashboard/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof ProtectedDashboardInstructorImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/instructor/_instructor': {
      id: '/_protected/_dashboard/instructor/_instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorImport
      parentRoute: typeof ProtectedDashboardInstructorRoute
    }
    '/_protected/_dashboard/student': {
      id: '/_protected/_dashboard/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof ProtectedDashboardStudentImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/student/_student': {
      id: '/_protected/_dashboard/student/_student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof ProtectedDashboardStudentStudentImport
      parentRoute: typeof ProtectedDashboardStudentRoute
    }
    '/_protected/_dashboard/instructor/_instructor/analytics': {
      id: '/_protected/_dashboard/instructor/_instructor/analytics'
      path: '/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorAnalyticsImport
      parentRoute: typeof ProtectedDashboardInstructorInstructorImport
    }
    '/_protected/_dashboard/instructor/_instructor/courses': {
      id: '/_protected/_dashboard/instructor/_instructor/courses'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorCoursesImport
      parentRoute: typeof ProtectedDashboardInstructorInstructorImport
    }
    '/_protected/_dashboard/list/students/$id': {
      id: '/_protected/_dashboard/list/students/$id'
      path: '/list/students/$id'
      fullPath: '/list/students/$id'
      preLoaderRoute: typeof ProtectedDashboardListStudentsIdImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/teachers/$id': {
      id: '/_protected/_dashboard/list/teachers/$id'
      path: '/list/teachers/$id'
      fullPath: '/list/teachers/$id'
      preLoaderRoute: typeof ProtectedDashboardListTeachersIdImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/admin/_admin/': {
      id: '/_protected/_dashboard/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/instructor/_instructor/': {
      id: '/_protected/_dashboard/instructor/_instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorIndexImport
      parentRoute: typeof ProtectedDashboardInstructorInstructorImport
    }
    '/_protected/_dashboard/list/announcements/': {
      id: '/_protected/_dashboard/list/announcements/'
      path: '/list/announcements'
      fullPath: '/list/announcements'
      preLoaderRoute: typeof ProtectedDashboardListAnnouncementsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/assignments/': {
      id: '/_protected/_dashboard/list/assignments/'
      path: '/list/assignments'
      fullPath: '/list/assignments'
      preLoaderRoute: typeof ProtectedDashboardListAssignmentsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/classes/': {
      id: '/_protected/_dashboard/list/classes/'
      path: '/list/classes'
      fullPath: '/list/classes'
      preLoaderRoute: typeof ProtectedDashboardListClassesIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/events/': {
      id: '/_protected/_dashboard/list/events/'
      path: '/list/events'
      fullPath: '/list/events'
      preLoaderRoute: typeof ProtectedDashboardListEventsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/exams/': {
      id: '/_protected/_dashboard/list/exams/'
      path: '/list/exams'
      fullPath: '/list/exams'
      preLoaderRoute: typeof ProtectedDashboardListExamsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/lessons/': {
      id: '/_protected/_dashboard/list/lessons/'
      path: '/list/lessons'
      fullPath: '/list/lessons'
      preLoaderRoute: typeof ProtectedDashboardListLessonsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/results/': {
      id: '/_protected/_dashboard/list/results/'
      path: '/list/results'
      fullPath: '/list/results'
      preLoaderRoute: typeof ProtectedDashboardListResultsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/students/': {
      id: '/_protected/_dashboard/list/students/'
      path: '/list/students'
      fullPath: '/list/students'
      preLoaderRoute: typeof ProtectedDashboardListStudentsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/subjects/': {
      id: '/_protected/_dashboard/list/subjects/'
      path: '/list/subjects'
      fullPath: '/list/subjects'
      preLoaderRoute: typeof ProtectedDashboardListSubjectsIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/list/teachers/': {
      id: '/_protected/_dashboard/list/teachers/'
      path: '/list/teachers'
      fullPath: '/list/teachers'
      preLoaderRoute: typeof ProtectedDashboardListTeachersIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/student/_student/': {
      id: '/_protected/_dashboard/student/_student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof ProtectedDashboardStudentStudentIndexImport
      parentRoute: typeof ProtectedDashboardStudentStudentImport
    }
  }
}

// Create and export the route tree

interface ProtectedDashboardAdminAdminRouteChildren {
  ProtectedDashboardAdminAdminIndexRoute: typeof ProtectedDashboardAdminAdminIndexRoute
}

const ProtectedDashboardAdminAdminRouteChildren: ProtectedDashboardAdminAdminRouteChildren =
  {
    ProtectedDashboardAdminAdminIndexRoute:
      ProtectedDashboardAdminAdminIndexRoute,
  }

const ProtectedDashboardAdminAdminRouteWithChildren =
  ProtectedDashboardAdminAdminRoute._addFileChildren(
    ProtectedDashboardAdminAdminRouteChildren,
  )

interface ProtectedDashboardAdminRouteChildren {
  ProtectedDashboardAdminAdminRoute: typeof ProtectedDashboardAdminAdminRouteWithChildren
}

const ProtectedDashboardAdminRouteChildren: ProtectedDashboardAdminRouteChildren =
  {
    ProtectedDashboardAdminAdminRoute:
      ProtectedDashboardAdminAdminRouteWithChildren,
  }

const ProtectedDashboardAdminRouteWithChildren =
  ProtectedDashboardAdminRoute._addFileChildren(
    ProtectedDashboardAdminRouteChildren,
  )

interface ProtectedDashboardInstructorInstructorRouteChildren {
  ProtectedDashboardInstructorInstructorAnalyticsRoute: typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  ProtectedDashboardInstructorInstructorCoursesRoute: typeof ProtectedDashboardInstructorInstructorCoursesRoute
  ProtectedDashboardInstructorInstructorIndexRoute: typeof ProtectedDashboardInstructorInstructorIndexRoute
}

const ProtectedDashboardInstructorInstructorRouteChildren: ProtectedDashboardInstructorInstructorRouteChildren =
  {
    ProtectedDashboardInstructorInstructorAnalyticsRoute:
      ProtectedDashboardInstructorInstructorAnalyticsRoute,
    ProtectedDashboardInstructorInstructorCoursesRoute:
      ProtectedDashboardInstructorInstructorCoursesRoute,
    ProtectedDashboardInstructorInstructorIndexRoute:
      ProtectedDashboardInstructorInstructorIndexRoute,
  }

const ProtectedDashboardInstructorInstructorRouteWithChildren =
  ProtectedDashboardInstructorInstructorRoute._addFileChildren(
    ProtectedDashboardInstructorInstructorRouteChildren,
  )

interface ProtectedDashboardInstructorRouteChildren {
  ProtectedDashboardInstructorInstructorRoute: typeof ProtectedDashboardInstructorInstructorRouteWithChildren
}

const ProtectedDashboardInstructorRouteChildren: ProtectedDashboardInstructorRouteChildren =
  {
    ProtectedDashboardInstructorInstructorRoute:
      ProtectedDashboardInstructorInstructorRouteWithChildren,
  }

const ProtectedDashboardInstructorRouteWithChildren =
  ProtectedDashboardInstructorRoute._addFileChildren(
    ProtectedDashboardInstructorRouteChildren,
  )

interface ProtectedDashboardStudentStudentRouteChildren {
  ProtectedDashboardStudentStudentIndexRoute: typeof ProtectedDashboardStudentStudentIndexRoute
}

const ProtectedDashboardStudentStudentRouteChildren: ProtectedDashboardStudentStudentRouteChildren =
  {
    ProtectedDashboardStudentStudentIndexRoute:
      ProtectedDashboardStudentStudentIndexRoute,
  }

const ProtectedDashboardStudentStudentRouteWithChildren =
  ProtectedDashboardStudentStudentRoute._addFileChildren(
    ProtectedDashboardStudentStudentRouteChildren,
  )

interface ProtectedDashboardStudentRouteChildren {
  ProtectedDashboardStudentStudentRoute: typeof ProtectedDashboardStudentStudentRouteWithChildren
}

const ProtectedDashboardStudentRouteChildren: ProtectedDashboardStudentRouteChildren =
  {
    ProtectedDashboardStudentStudentRoute:
      ProtectedDashboardStudentStudentRouteWithChildren,
  }

const ProtectedDashboardStudentRouteWithChildren =
  ProtectedDashboardStudentRoute._addFileChildren(
    ProtectedDashboardStudentRouteChildren,
  )

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardAnnouncementsLazyRoute: typeof ProtectedDashboardAnnouncementsLazyRoute
  ProtectedDashboardAdminRoute: typeof ProtectedDashboardAdminRouteWithChildren
  ProtectedDashboardInstructorRoute: typeof ProtectedDashboardInstructorRouteWithChildren
  ProtectedDashboardStudentRoute: typeof ProtectedDashboardStudentRouteWithChildren
  ProtectedDashboardListStudentsIdRoute: typeof ProtectedDashboardListStudentsIdRoute
  ProtectedDashboardListTeachersIdRoute: typeof ProtectedDashboardListTeachersIdRoute
  ProtectedDashboardListAnnouncementsIndexRoute: typeof ProtectedDashboardListAnnouncementsIndexRoute
  ProtectedDashboardListAssignmentsIndexRoute: typeof ProtectedDashboardListAssignmentsIndexRoute
  ProtectedDashboardListClassesIndexRoute: typeof ProtectedDashboardListClassesIndexRoute
  ProtectedDashboardListEventsIndexRoute: typeof ProtectedDashboardListEventsIndexRoute
  ProtectedDashboardListExamsIndexRoute: typeof ProtectedDashboardListExamsIndexRoute
  ProtectedDashboardListLessonsIndexRoute: typeof ProtectedDashboardListLessonsIndexRoute
  ProtectedDashboardListResultsIndexRoute: typeof ProtectedDashboardListResultsIndexRoute
  ProtectedDashboardListStudentsIndexRoute: typeof ProtectedDashboardListStudentsIndexRoute
  ProtectedDashboardListSubjectsIndexRoute: typeof ProtectedDashboardListSubjectsIndexRoute
  ProtectedDashboardListTeachersIndexRoute: typeof ProtectedDashboardListTeachersIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardAnnouncementsLazyRoute:
    ProtectedDashboardAnnouncementsLazyRoute,
  ProtectedDashboardAdminRoute: ProtectedDashboardAdminRouteWithChildren,
  ProtectedDashboardInstructorRoute:
    ProtectedDashboardInstructorRouteWithChildren,
  ProtectedDashboardStudentRoute: ProtectedDashboardStudentRouteWithChildren,
  ProtectedDashboardListStudentsIdRoute: ProtectedDashboardListStudentsIdRoute,
  ProtectedDashboardListTeachersIdRoute: ProtectedDashboardListTeachersIdRoute,
  ProtectedDashboardListAnnouncementsIndexRoute:
    ProtectedDashboardListAnnouncementsIndexRoute,
  ProtectedDashboardListAssignmentsIndexRoute:
    ProtectedDashboardListAssignmentsIndexRoute,
  ProtectedDashboardListClassesIndexRoute:
    ProtectedDashboardListClassesIndexRoute,
  ProtectedDashboardListEventsIndexRoute:
    ProtectedDashboardListEventsIndexRoute,
  ProtectedDashboardListExamsIndexRoute: ProtectedDashboardListExamsIndexRoute,
  ProtectedDashboardListLessonsIndexRoute:
    ProtectedDashboardListLessonsIndexRoute,
  ProtectedDashboardListResultsIndexRoute:
    ProtectedDashboardListResultsIndexRoute,
  ProtectedDashboardListStudentsIndexRoute:
    ProtectedDashboardListStudentsIndexRoute,
  ProtectedDashboardListSubjectsIndexRoute:
    ProtectedDashboardListSubjectsIndexRoute,
  ProtectedDashboardListTeachersIndexRoute:
    ProtectedDashboardListTeachersIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof ProtectedIndexRoute
  '/announcements': typeof ProtectedDashboardAnnouncementsLazyRoute
  '/admin': typeof ProtectedDashboardAdminAdminRouteWithChildren
  '/instructor': typeof ProtectedDashboardInstructorInstructorRouteWithChildren
  '/student': typeof ProtectedDashboardStudentStudentRouteWithChildren
  '/instructor/analytics': typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  '/instructor/courses': typeof ProtectedDashboardInstructorInstructorCoursesRoute
  '/list/students/$id': typeof ProtectedDashboardListStudentsIdRoute
  '/list/teachers/$id': typeof ProtectedDashboardListTeachersIdRoute
  '/admin/': typeof ProtectedDashboardAdminAdminIndexRoute
  '/instructor/': typeof ProtectedDashboardInstructorInstructorIndexRoute
  '/list/announcements': typeof ProtectedDashboardListAnnouncementsIndexRoute
  '/list/assignments': typeof ProtectedDashboardListAssignmentsIndexRoute
  '/list/classes': typeof ProtectedDashboardListClassesIndexRoute
  '/list/events': typeof ProtectedDashboardListEventsIndexRoute
  '/list/exams': typeof ProtectedDashboardListExamsIndexRoute
  '/list/lessons': typeof ProtectedDashboardListLessonsIndexRoute
  '/list/results': typeof ProtectedDashboardListResultsIndexRoute
  '/list/students': typeof ProtectedDashboardListStudentsIndexRoute
  '/list/subjects': typeof ProtectedDashboardListSubjectsIndexRoute
  '/list/teachers': typeof ProtectedDashboardListTeachersIndexRoute
  '/student/': typeof ProtectedDashboardStudentStudentIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '': typeof ProtectedDashboardRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/announcements': typeof ProtectedDashboardAnnouncementsLazyRoute
  '/admin': typeof ProtectedDashboardAdminAdminIndexRoute
  '/instructor': typeof ProtectedDashboardInstructorInstructorIndexRoute
  '/student': typeof ProtectedDashboardStudentStudentIndexRoute
  '/instructor/analytics': typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  '/instructor/courses': typeof ProtectedDashboardInstructorInstructorCoursesRoute
  '/list/students/$id': typeof ProtectedDashboardListStudentsIdRoute
  '/list/teachers/$id': typeof ProtectedDashboardListTeachersIdRoute
  '/list/announcements': typeof ProtectedDashboardListAnnouncementsIndexRoute
  '/list/assignments': typeof ProtectedDashboardListAssignmentsIndexRoute
  '/list/classes': typeof ProtectedDashboardListClassesIndexRoute
  '/list/events': typeof ProtectedDashboardListEventsIndexRoute
  '/list/exams': typeof ProtectedDashboardListExamsIndexRoute
  '/list/lessons': typeof ProtectedDashboardListLessonsIndexRoute
  '/list/results': typeof ProtectedDashboardListResultsIndexRoute
  '/list/students': typeof ProtectedDashboardListStudentsIndexRoute
  '/list/subjects': typeof ProtectedDashboardListSubjectsIndexRoute
  '/list/teachers': typeof ProtectedDashboardListTeachersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/_dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/_dashboard/announcements': typeof ProtectedDashboardAnnouncementsLazyRoute
  '/_protected/_dashboard/admin': typeof ProtectedDashboardAdminRouteWithChildren
  '/_protected/_dashboard/admin/_admin': typeof ProtectedDashboardAdminAdminRouteWithChildren
  '/_protected/_dashboard/instructor': typeof ProtectedDashboardInstructorRouteWithChildren
  '/_protected/_dashboard/instructor/_instructor': typeof ProtectedDashboardInstructorInstructorRouteWithChildren
  '/_protected/_dashboard/student': typeof ProtectedDashboardStudentRouteWithChildren
  '/_protected/_dashboard/student/_student': typeof ProtectedDashboardStudentStudentRouteWithChildren
  '/_protected/_dashboard/instructor/_instructor/analytics': typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  '/_protected/_dashboard/instructor/_instructor/courses': typeof ProtectedDashboardInstructorInstructorCoursesRoute
  '/_protected/_dashboard/list/students/$id': typeof ProtectedDashboardListStudentsIdRoute
  '/_protected/_dashboard/list/teachers/$id': typeof ProtectedDashboardListTeachersIdRoute
  '/_protected/_dashboard/admin/_admin/': typeof ProtectedDashboardAdminAdminIndexRoute
  '/_protected/_dashboard/instructor/_instructor/': typeof ProtectedDashboardInstructorInstructorIndexRoute
  '/_protected/_dashboard/list/announcements/': typeof ProtectedDashboardListAnnouncementsIndexRoute
  '/_protected/_dashboard/list/assignments/': typeof ProtectedDashboardListAssignmentsIndexRoute
  '/_protected/_dashboard/list/classes/': typeof ProtectedDashboardListClassesIndexRoute
  '/_protected/_dashboard/list/events/': typeof ProtectedDashboardListEventsIndexRoute
  '/_protected/_dashboard/list/exams/': typeof ProtectedDashboardListExamsIndexRoute
  '/_protected/_dashboard/list/lessons/': typeof ProtectedDashboardListLessonsIndexRoute
  '/_protected/_dashboard/list/results/': typeof ProtectedDashboardListResultsIndexRoute
  '/_protected/_dashboard/list/students/': typeof ProtectedDashboardListStudentsIndexRoute
  '/_protected/_dashboard/list/subjects/': typeof ProtectedDashboardListSubjectsIndexRoute
  '/_protected/_dashboard/list/teachers/': typeof ProtectedDashboardListTeachersIndexRoute
  '/_protected/_dashboard/student/_student/': typeof ProtectedDashboardStudentStudentIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/announcements'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/list/students/$id'
    | '/list/teachers/$id'
    | '/admin/'
    | '/instructor/'
    | '/list/announcements'
    | '/list/assignments'
    | '/list/classes'
    | '/list/events'
    | '/list/exams'
    | '/list/lessons'
    | '/list/results'
    | '/list/students'
    | '/list/subjects'
    | '/list/teachers'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | ''
    | '/'
    | '/announcements'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/list/students/$id'
    | '/list/teachers/$id'
    | '/list/announcements'
    | '/list/assignments'
    | '/list/classes'
    | '/list/events'
    | '/list/exams'
    | '/list/lessons'
    | '/list/results'
    | '/list/students'
    | '/list/subjects'
    | '/list/teachers'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/register'
    | '/_protected/_dashboard'
    | '/_protected/'
    | '/_protected/_dashboard/announcements'
    | '/_protected/_dashboard/admin'
    | '/_protected/_dashboard/admin/_admin'
    | '/_protected/_dashboard/instructor'
    | '/_protected/_dashboard/instructor/_instructor'
    | '/_protected/_dashboard/student'
    | '/_protected/_dashboard/student/_student'
    | '/_protected/_dashboard/instructor/_instructor/analytics'
    | '/_protected/_dashboard/instructor/_instructor/courses'
    | '/_protected/_dashboard/list/students/$id'
    | '/_protected/_dashboard/list/teachers/$id'
    | '/_protected/_dashboard/admin/_admin/'
    | '/_protected/_dashboard/instructor/_instructor/'
    | '/_protected/_dashboard/list/announcements/'
    | '/_protected/_dashboard/list/assignments/'
    | '/_protected/_dashboard/list/classes/'
    | '/_protected/_dashboard/list/events/'
    | '/_protected/_dashboard/list/exams/'
    | '/_protected/_dashboard/list/lessons/'
    | '/_protected/_dashboard/list/results/'
    | '/_protected/_dashboard/list/students/'
    | '/_protected/_dashboard/list/subjects/'
    | '/_protected/_dashboard/list/teachers/'
    | '/_protected/_dashboard/student/_student/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/login",
        "/register"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/_dashboard",
        "/_protected/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_protected/_dashboard": {
      "filePath": "_protected/_dashboard.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/_dashboard/announcements",
        "/_protected/_dashboard/admin",
        "/_protected/_dashboard/instructor",
        "/_protected/_dashboard/student",
        "/_protected/_dashboard/list/students/$id",
        "/_protected/_dashboard/list/teachers/$id",
        "/_protected/_dashboard/list/announcements/",
        "/_protected/_dashboard/list/assignments/",
        "/_protected/_dashboard/list/classes/",
        "/_protected/_dashboard/list/events/",
        "/_protected/_dashboard/list/exams/",
        "/_protected/_dashboard/list/lessons/",
        "/_protected/_dashboard/list/results/",
        "/_protected/_dashboard/list/students/",
        "/_protected/_dashboard/list/subjects/",
        "/_protected/_dashboard/list/teachers/"
      ]
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/_dashboard/announcements": {
      "filePath": "_protected/_dashboard/announcements.lazy.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/admin": {
      "filePath": "_protected/_dashboard/admin",
      "parent": "/_protected/_dashboard",
      "children": [
        "/_protected/_dashboard/admin/_admin"
      ]
    },
    "/_protected/_dashboard/admin/_admin": {
      "filePath": "_protected/_dashboard/admin/_admin.tsx",
      "parent": "/_protected/_dashboard/admin",
      "children": [
        "/_protected/_dashboard/admin/_admin/"
      ]
    },
    "/_protected/_dashboard/instructor": {
      "filePath": "_protected/_dashboard/instructor",
      "parent": "/_protected/_dashboard",
      "children": [
        "/_protected/_dashboard/instructor/_instructor"
      ]
    },
    "/_protected/_dashboard/instructor/_instructor": {
      "filePath": "_protected/_dashboard/instructor/_instructor.tsx",
      "parent": "/_protected/_dashboard/instructor",
      "children": [
        "/_protected/_dashboard/instructor/_instructor/analytics",
        "/_protected/_dashboard/instructor/_instructor/courses",
        "/_protected/_dashboard/instructor/_instructor/"
      ]
    },
    "/_protected/_dashboard/student": {
      "filePath": "_protected/_dashboard/student",
      "parent": "/_protected/_dashboard",
      "children": [
        "/_protected/_dashboard/student/_student"
      ]
    },
    "/_protected/_dashboard/student/_student": {
      "filePath": "_protected/_dashboard/student/_student.tsx",
      "parent": "/_protected/_dashboard/student",
      "children": [
        "/_protected/_dashboard/student/_student/"
      ]
    },
    "/_protected/_dashboard/instructor/_instructor/analytics": {
      "filePath": "_protected/_dashboard/instructor/_instructor/analytics.tsx",
      "parent": "/_protected/_dashboard/instructor/_instructor"
    },
    "/_protected/_dashboard/instructor/_instructor/courses": {
      "filePath": "_protected/_dashboard/instructor/_instructor/courses.tsx",
      "parent": "/_protected/_dashboard/instructor/_instructor"
    },
    "/_protected/_dashboard/list/students/$id": {
      "filePath": "_protected/_dashboard/list/students/$id.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/teachers/$id": {
      "filePath": "_protected/_dashboard/list/teachers/$id.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/admin/_admin/": {
      "filePath": "_protected/_dashboard/admin/_admin/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/instructor/_instructor/": {
      "filePath": "_protected/_dashboard/instructor/_instructor/index.tsx",
      "parent": "/_protected/_dashboard/instructor/_instructor"
    },
    "/_protected/_dashboard/list/announcements/": {
      "filePath": "_protected/_dashboard/list/announcements/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/assignments/": {
      "filePath": "_protected/_dashboard/list/assignments/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/classes/": {
      "filePath": "_protected/_dashboard/list/classes/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/events/": {
      "filePath": "_protected/_dashboard/list/events/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/exams/": {
      "filePath": "_protected/_dashboard/list/exams/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/lessons/": {
      "filePath": "_protected/_dashboard/list/lessons/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/results/": {
      "filePath": "_protected/_dashboard/list/results/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/students/": {
      "filePath": "_protected/_dashboard/list/students/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/subjects/": {
      "filePath": "_protected/_dashboard/list/subjects/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/list/teachers/": {
      "filePath": "_protected/_dashboard/list/teachers/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/student/_student/": {
      "filePath": "_protected/_dashboard/student/_student/index.tsx",
      "parent": "/_protected/_dashboard/student/_student"
    }
  }
}
ROUTE_MANIFEST_END */
