/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedDashboardImport } from './routes/_protected/_dashboard'
import { Route as ProtectedDashboardStudentStudentImport } from './routes/_protected/_dashboard/student/_student'
import { Route as ProtectedDashboardInstructorInstructorImport } from './routes/_protected/_dashboard/instructor/_instructor'
import { Route as ProtectedDashboardAdminAdminImport } from './routes/_protected/_dashboard/admin/_admin'
import { Route as ProtectedDashboardStudentStudentIndexImport } from './routes/_protected/_dashboard/student/_student/index'
import { Route as ProtectedDashboardInstructorInstructorIndexImport } from './routes/_protected/_dashboard/instructor/_instructor/index'
import { Route as ProtectedDashboardAdminAdminIndexImport } from './routes/_protected/_dashboard/admin/_admin/index'
import { Route as ProtectedDashboardInstructorInstructorCoursesImport } from './routes/_protected/_dashboard/instructor/_instructor/courses'
import { Route as ProtectedDashboardInstructorInstructorAnalyticsImport } from './routes/_protected/_dashboard/instructor/_instructor/analytics'
import { Route as ProtectedDashboardAdminAdminListTeachersIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/teachers/index'
import { Route as ProtectedDashboardAdminAdminListSubjectsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/subjects/index'
import { Route as ProtectedDashboardAdminAdminListStudentsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/students/index'
import { Route as ProtectedDashboardAdminAdminListResultsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/results/index'
import { Route as ProtectedDashboardAdminAdminListLessonsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/lessons/index'
import { Route as ProtectedDashboardAdminAdminListExamsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/exams/index'
import { Route as ProtectedDashboardAdminAdminListEventsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/events/index'
import { Route as ProtectedDashboardAdminAdminListClassesIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/classes/index'
import { Route as ProtectedDashboardAdminAdminListAssignmentsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/assignments/index'
import { Route as ProtectedDashboardAdminAdminListAnnouncementsIndexImport } from './routes/_protected/_dashboard/admin/_admin/list/announcements/index'
import { Route as ProtectedDashboardAdminAdminListTeachersIdImport } from './routes/_protected/_dashboard/admin/_admin/list/teachers/$id'
import { Route as ProtectedDashboardAdminAdminListStudentsIdImport } from './routes/_protected/_dashboard/admin/_admin/list/students/$id'

// Create Virtual Routes

const ProtectedDashboardStudentImport = createFileRoute(
  '/_protected/_dashboard/student',
)()
const ProtectedDashboardInstructorImport = createFileRoute(
  '/_protected/_dashboard/instructor',
)()
const ProtectedDashboardAdminImport = createFileRoute(
  '/_protected/_dashboard/admin',
)()
const ProtectedDashboardAnnouncementsLazyImport = createFileRoute(
  '/_protected/_dashboard/announcements',
)()

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedDashboardStudentRoute = ProtectedDashboardStudentImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)

const ProtectedDashboardInstructorRoute =
  ProtectedDashboardInstructorImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardAdminRoute = ProtectedDashboardAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)

const ProtectedDashboardAnnouncementsLazyRoute =
  ProtectedDashboardAnnouncementsLazyImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_protected/_dashboard/announcements.lazy').then(
      (d) => d.Route,
    ),
  )

const ProtectedDashboardStudentStudentRoute =
  ProtectedDashboardStudentStudentImport.update({
    id: '/_student',
    getParentRoute: () => ProtectedDashboardStudentRoute,
  } as any)

const ProtectedDashboardInstructorInstructorRoute =
  ProtectedDashboardInstructorInstructorImport.update({
    id: '/_instructor',
    getParentRoute: () => ProtectedDashboardInstructorRoute,
  } as any)

const ProtectedDashboardAdminAdminRoute =
  ProtectedDashboardAdminAdminImport.update({
    id: '/_admin',
    getParentRoute: () => ProtectedDashboardAdminRoute,
  } as any)

const ProtectedDashboardStudentStudentIndexRoute =
  ProtectedDashboardStudentStudentIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardStudentStudentRoute,
  } as any)

const ProtectedDashboardInstructorInstructorIndexRoute =
  ProtectedDashboardInstructorInstructorIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardInstructorInstructorRoute,
  } as any)

const ProtectedDashboardAdminAdminIndexRoute =
  ProtectedDashboardAdminAdminIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardInstructorInstructorCoursesRoute =
  ProtectedDashboardInstructorInstructorCoursesImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => ProtectedDashboardInstructorInstructorRoute,
  } as any)

const ProtectedDashboardInstructorInstructorAnalyticsRoute =
  ProtectedDashboardInstructorInstructorAnalyticsImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ProtectedDashboardInstructorInstructorRoute,
  } as any)

const ProtectedDashboardAdminAdminListTeachersIndexRoute =
  ProtectedDashboardAdminAdminListTeachersIndexImport.update({
    id: '/list/teachers/',
    path: '/list/teachers/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListSubjectsIndexRoute =
  ProtectedDashboardAdminAdminListSubjectsIndexImport.update({
    id: '/list/subjects/',
    path: '/list/subjects/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListStudentsIndexRoute =
  ProtectedDashboardAdminAdminListStudentsIndexImport.update({
    id: '/list/students/',
    path: '/list/students/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListResultsIndexRoute =
  ProtectedDashboardAdminAdminListResultsIndexImport.update({
    id: '/list/results/',
    path: '/list/results/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListLessonsIndexRoute =
  ProtectedDashboardAdminAdminListLessonsIndexImport.update({
    id: '/list/lessons/',
    path: '/list/lessons/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListExamsIndexRoute =
  ProtectedDashboardAdminAdminListExamsIndexImport.update({
    id: '/list/exams/',
    path: '/list/exams/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListEventsIndexRoute =
  ProtectedDashboardAdminAdminListEventsIndexImport.update({
    id: '/list/events/',
    path: '/list/events/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListClassesIndexRoute =
  ProtectedDashboardAdminAdminListClassesIndexImport.update({
    id: '/list/classes/',
    path: '/list/classes/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListAssignmentsIndexRoute =
  ProtectedDashboardAdminAdminListAssignmentsIndexImport.update({
    id: '/list/assignments/',
    path: '/list/assignments/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListAnnouncementsIndexRoute =
  ProtectedDashboardAdminAdminListAnnouncementsIndexImport.update({
    id: '/list/announcements/',
    path: '/list/announcements/',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListTeachersIdRoute =
  ProtectedDashboardAdminAdminListTeachersIdImport.update({
    id: '/list/teachers/$id',
    path: '/list/teachers/$id',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

const ProtectedDashboardAdminAdminListStudentsIdRoute =
  ProtectedDashboardAdminAdminListStudentsIdImport.update({
    id: '/list/students/$id',
    path: '/list/students/$id',
    getParentRoute: () => ProtectedDashboardAdminAdminRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_protected/_dashboard': {
      id: '/_protected/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/_dashboard/announcements': {
      id: '/_protected/_dashboard/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof ProtectedDashboardAnnouncementsLazyImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/admin': {
      id: '/_protected/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedDashboardAdminImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/admin/_admin': {
      id: '/_protected/_dashboard/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminImport
      parentRoute: typeof ProtectedDashboardAdminRoute
    }
    '/_protected/_dashboard/instructor': {
      id: '/_protected/_dashboard/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof ProtectedDashboardInstructorImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/instructor/_instructor': {
      id: '/_protected/_dashboard/instructor/_instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorImport
      parentRoute: typeof ProtectedDashboardInstructorRoute
    }
    '/_protected/_dashboard/student': {
      id: '/_protected/_dashboard/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof ProtectedDashboardStudentImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/student/_student': {
      id: '/_protected/_dashboard/student/_student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof ProtectedDashboardStudentStudentImport
      parentRoute: typeof ProtectedDashboardStudentRoute
    }
    '/_protected/_dashboard/instructor/_instructor/analytics': {
      id: '/_protected/_dashboard/instructor/_instructor/analytics'
      path: '/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorAnalyticsImport
      parentRoute: typeof ProtectedDashboardInstructorInstructorImport
    }
    '/_protected/_dashboard/instructor/_instructor/courses': {
      id: '/_protected/_dashboard/instructor/_instructor/courses'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorCoursesImport
      parentRoute: typeof ProtectedDashboardInstructorInstructorImport
    }
    '/_protected/_dashboard/admin/_admin/': {
      id: '/_protected/_dashboard/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/instructor/_instructor/': {
      id: '/_protected/_dashboard/instructor/_instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof ProtectedDashboardInstructorInstructorIndexImport
      parentRoute: typeof ProtectedDashboardInstructorInstructorImport
    }
    '/_protected/_dashboard/student/_student/': {
      id: '/_protected/_dashboard/student/_student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof ProtectedDashboardStudentStudentIndexImport
      parentRoute: typeof ProtectedDashboardStudentStudentImport
    }
    '/_protected/_dashboard/admin/_admin/list/students/$id': {
      id: '/_protected/_dashboard/admin/_admin/list/students/$id'
      path: '/list/students/$id'
      fullPath: '/admin/list/students/$id'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListStudentsIdImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/teachers/$id': {
      id: '/_protected/_dashboard/admin/_admin/list/teachers/$id'
      path: '/list/teachers/$id'
      fullPath: '/admin/list/teachers/$id'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListTeachersIdImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/announcements/': {
      id: '/_protected/_dashboard/admin/_admin/list/announcements/'
      path: '/list/announcements'
      fullPath: '/admin/list/announcements'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListAnnouncementsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/assignments/': {
      id: '/_protected/_dashboard/admin/_admin/list/assignments/'
      path: '/list/assignments'
      fullPath: '/admin/list/assignments'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListAssignmentsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/classes/': {
      id: '/_protected/_dashboard/admin/_admin/list/classes/'
      path: '/list/classes'
      fullPath: '/admin/list/classes'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListClassesIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/events/': {
      id: '/_protected/_dashboard/admin/_admin/list/events/'
      path: '/list/events'
      fullPath: '/admin/list/events'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListEventsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/exams/': {
      id: '/_protected/_dashboard/admin/_admin/list/exams/'
      path: '/list/exams'
      fullPath: '/admin/list/exams'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListExamsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/lessons/': {
      id: '/_protected/_dashboard/admin/_admin/list/lessons/'
      path: '/list/lessons'
      fullPath: '/admin/list/lessons'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListLessonsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/results/': {
      id: '/_protected/_dashboard/admin/_admin/list/results/'
      path: '/list/results'
      fullPath: '/admin/list/results'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListResultsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/students/': {
      id: '/_protected/_dashboard/admin/_admin/list/students/'
      path: '/list/students'
      fullPath: '/admin/list/students'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListStudentsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/subjects/': {
      id: '/_protected/_dashboard/admin/_admin/list/subjects/'
      path: '/list/subjects'
      fullPath: '/admin/list/subjects'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListSubjectsIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
    '/_protected/_dashboard/admin/_admin/list/teachers/': {
      id: '/_protected/_dashboard/admin/_admin/list/teachers/'
      path: '/list/teachers'
      fullPath: '/admin/list/teachers'
      preLoaderRoute: typeof ProtectedDashboardAdminAdminListTeachersIndexImport
      parentRoute: typeof ProtectedDashboardAdminAdminImport
    }
  }
}

// Create and export the route tree

interface ProtectedDashboardAdminAdminRouteChildren {
  ProtectedDashboardAdminAdminIndexRoute: typeof ProtectedDashboardAdminAdminIndexRoute
  ProtectedDashboardAdminAdminListStudentsIdRoute: typeof ProtectedDashboardAdminAdminListStudentsIdRoute
  ProtectedDashboardAdminAdminListTeachersIdRoute: typeof ProtectedDashboardAdminAdminListTeachersIdRoute
  ProtectedDashboardAdminAdminListAnnouncementsIndexRoute: typeof ProtectedDashboardAdminAdminListAnnouncementsIndexRoute
  ProtectedDashboardAdminAdminListAssignmentsIndexRoute: typeof ProtectedDashboardAdminAdminListAssignmentsIndexRoute
  ProtectedDashboardAdminAdminListClassesIndexRoute: typeof ProtectedDashboardAdminAdminListClassesIndexRoute
  ProtectedDashboardAdminAdminListEventsIndexRoute: typeof ProtectedDashboardAdminAdminListEventsIndexRoute
  ProtectedDashboardAdminAdminListExamsIndexRoute: typeof ProtectedDashboardAdminAdminListExamsIndexRoute
  ProtectedDashboardAdminAdminListLessonsIndexRoute: typeof ProtectedDashboardAdminAdminListLessonsIndexRoute
  ProtectedDashboardAdminAdminListResultsIndexRoute: typeof ProtectedDashboardAdminAdminListResultsIndexRoute
  ProtectedDashboardAdminAdminListStudentsIndexRoute: typeof ProtectedDashboardAdminAdminListStudentsIndexRoute
  ProtectedDashboardAdminAdminListSubjectsIndexRoute: typeof ProtectedDashboardAdminAdminListSubjectsIndexRoute
  ProtectedDashboardAdminAdminListTeachersIndexRoute: typeof ProtectedDashboardAdminAdminListTeachersIndexRoute
}

const ProtectedDashboardAdminAdminRouteChildren: ProtectedDashboardAdminAdminRouteChildren =
  {
    ProtectedDashboardAdminAdminIndexRoute:
      ProtectedDashboardAdminAdminIndexRoute,
    ProtectedDashboardAdminAdminListStudentsIdRoute:
      ProtectedDashboardAdminAdminListStudentsIdRoute,
    ProtectedDashboardAdminAdminListTeachersIdRoute:
      ProtectedDashboardAdminAdminListTeachersIdRoute,
    ProtectedDashboardAdminAdminListAnnouncementsIndexRoute:
      ProtectedDashboardAdminAdminListAnnouncementsIndexRoute,
    ProtectedDashboardAdminAdminListAssignmentsIndexRoute:
      ProtectedDashboardAdminAdminListAssignmentsIndexRoute,
    ProtectedDashboardAdminAdminListClassesIndexRoute:
      ProtectedDashboardAdminAdminListClassesIndexRoute,
    ProtectedDashboardAdminAdminListEventsIndexRoute:
      ProtectedDashboardAdminAdminListEventsIndexRoute,
    ProtectedDashboardAdminAdminListExamsIndexRoute:
      ProtectedDashboardAdminAdminListExamsIndexRoute,
    ProtectedDashboardAdminAdminListLessonsIndexRoute:
      ProtectedDashboardAdminAdminListLessonsIndexRoute,
    ProtectedDashboardAdminAdminListResultsIndexRoute:
      ProtectedDashboardAdminAdminListResultsIndexRoute,
    ProtectedDashboardAdminAdminListStudentsIndexRoute:
      ProtectedDashboardAdminAdminListStudentsIndexRoute,
    ProtectedDashboardAdminAdminListSubjectsIndexRoute:
      ProtectedDashboardAdminAdminListSubjectsIndexRoute,
    ProtectedDashboardAdminAdminListTeachersIndexRoute:
      ProtectedDashboardAdminAdminListTeachersIndexRoute,
  }

const ProtectedDashboardAdminAdminRouteWithChildren =
  ProtectedDashboardAdminAdminRoute._addFileChildren(
    ProtectedDashboardAdminAdminRouteChildren,
  )

interface ProtectedDashboardAdminRouteChildren {
  ProtectedDashboardAdminAdminRoute: typeof ProtectedDashboardAdminAdminRouteWithChildren
}

const ProtectedDashboardAdminRouteChildren: ProtectedDashboardAdminRouteChildren =
  {
    ProtectedDashboardAdminAdminRoute:
      ProtectedDashboardAdminAdminRouteWithChildren,
  }

const ProtectedDashboardAdminRouteWithChildren =
  ProtectedDashboardAdminRoute._addFileChildren(
    ProtectedDashboardAdminRouteChildren,
  )

interface ProtectedDashboardInstructorInstructorRouteChildren {
  ProtectedDashboardInstructorInstructorAnalyticsRoute: typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  ProtectedDashboardInstructorInstructorCoursesRoute: typeof ProtectedDashboardInstructorInstructorCoursesRoute
  ProtectedDashboardInstructorInstructorIndexRoute: typeof ProtectedDashboardInstructorInstructorIndexRoute
}

const ProtectedDashboardInstructorInstructorRouteChildren: ProtectedDashboardInstructorInstructorRouteChildren =
  {
    ProtectedDashboardInstructorInstructorAnalyticsRoute:
      ProtectedDashboardInstructorInstructorAnalyticsRoute,
    ProtectedDashboardInstructorInstructorCoursesRoute:
      ProtectedDashboardInstructorInstructorCoursesRoute,
    ProtectedDashboardInstructorInstructorIndexRoute:
      ProtectedDashboardInstructorInstructorIndexRoute,
  }

const ProtectedDashboardInstructorInstructorRouteWithChildren =
  ProtectedDashboardInstructorInstructorRoute._addFileChildren(
    ProtectedDashboardInstructorInstructorRouteChildren,
  )

interface ProtectedDashboardInstructorRouteChildren {
  ProtectedDashboardInstructorInstructorRoute: typeof ProtectedDashboardInstructorInstructorRouteWithChildren
}

const ProtectedDashboardInstructorRouteChildren: ProtectedDashboardInstructorRouteChildren =
  {
    ProtectedDashboardInstructorInstructorRoute:
      ProtectedDashboardInstructorInstructorRouteWithChildren,
  }

const ProtectedDashboardInstructorRouteWithChildren =
  ProtectedDashboardInstructorRoute._addFileChildren(
    ProtectedDashboardInstructorRouteChildren,
  )

interface ProtectedDashboardStudentStudentRouteChildren {
  ProtectedDashboardStudentStudentIndexRoute: typeof ProtectedDashboardStudentStudentIndexRoute
}

const ProtectedDashboardStudentStudentRouteChildren: ProtectedDashboardStudentStudentRouteChildren =
  {
    ProtectedDashboardStudentStudentIndexRoute:
      ProtectedDashboardStudentStudentIndexRoute,
  }

const ProtectedDashboardStudentStudentRouteWithChildren =
  ProtectedDashboardStudentStudentRoute._addFileChildren(
    ProtectedDashboardStudentStudentRouteChildren,
  )

interface ProtectedDashboardStudentRouteChildren {
  ProtectedDashboardStudentStudentRoute: typeof ProtectedDashboardStudentStudentRouteWithChildren
}

const ProtectedDashboardStudentRouteChildren: ProtectedDashboardStudentRouteChildren =
  {
    ProtectedDashboardStudentStudentRoute:
      ProtectedDashboardStudentStudentRouteWithChildren,
  }

const ProtectedDashboardStudentRouteWithChildren =
  ProtectedDashboardStudentRoute._addFileChildren(
    ProtectedDashboardStudentRouteChildren,
  )

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardAnnouncementsLazyRoute: typeof ProtectedDashboardAnnouncementsLazyRoute
  ProtectedDashboardAdminRoute: typeof ProtectedDashboardAdminRouteWithChildren
  ProtectedDashboardInstructorRoute: typeof ProtectedDashboardInstructorRouteWithChildren
  ProtectedDashboardStudentRoute: typeof ProtectedDashboardStudentRouteWithChildren
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardAnnouncementsLazyRoute:
    ProtectedDashboardAnnouncementsLazyRoute,
  ProtectedDashboardAdminRoute: ProtectedDashboardAdminRouteWithChildren,
  ProtectedDashboardInstructorRoute:
    ProtectedDashboardInstructorRouteWithChildren,
  ProtectedDashboardStudentRoute: ProtectedDashboardStudentRouteWithChildren,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedDashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof ProtectedIndexRoute
  '/announcements': typeof ProtectedDashboardAnnouncementsLazyRoute
  '/admin': typeof ProtectedDashboardAdminAdminRouteWithChildren
  '/instructor': typeof ProtectedDashboardInstructorInstructorRouteWithChildren
  '/student': typeof ProtectedDashboardStudentStudentRouteWithChildren
  '/instructor/analytics': typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  '/instructor/courses': typeof ProtectedDashboardInstructorInstructorCoursesRoute
  '/admin/': typeof ProtectedDashboardAdminAdminIndexRoute
  '/instructor/': typeof ProtectedDashboardInstructorInstructorIndexRoute
  '/student/': typeof ProtectedDashboardStudentStudentIndexRoute
  '/admin/list/students/$id': typeof ProtectedDashboardAdminAdminListStudentsIdRoute
  '/admin/list/teachers/$id': typeof ProtectedDashboardAdminAdminListTeachersIdRoute
  '/admin/list/announcements': typeof ProtectedDashboardAdminAdminListAnnouncementsIndexRoute
  '/admin/list/assignments': typeof ProtectedDashboardAdminAdminListAssignmentsIndexRoute
  '/admin/list/classes': typeof ProtectedDashboardAdminAdminListClassesIndexRoute
  '/admin/list/events': typeof ProtectedDashboardAdminAdminListEventsIndexRoute
  '/admin/list/exams': typeof ProtectedDashboardAdminAdminListExamsIndexRoute
  '/admin/list/lessons': typeof ProtectedDashboardAdminAdminListLessonsIndexRoute
  '/admin/list/results': typeof ProtectedDashboardAdminAdminListResultsIndexRoute
  '/admin/list/students': typeof ProtectedDashboardAdminAdminListStudentsIndexRoute
  '/admin/list/subjects': typeof ProtectedDashboardAdminAdminListSubjectsIndexRoute
  '/admin/list/teachers': typeof ProtectedDashboardAdminAdminListTeachersIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '': typeof ProtectedDashboardRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/announcements': typeof ProtectedDashboardAnnouncementsLazyRoute
  '/admin': typeof ProtectedDashboardAdminAdminIndexRoute
  '/instructor': typeof ProtectedDashboardInstructorInstructorIndexRoute
  '/student': typeof ProtectedDashboardStudentStudentIndexRoute
  '/instructor/analytics': typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  '/instructor/courses': typeof ProtectedDashboardInstructorInstructorCoursesRoute
  '/admin/list/students/$id': typeof ProtectedDashboardAdminAdminListStudentsIdRoute
  '/admin/list/teachers/$id': typeof ProtectedDashboardAdminAdminListTeachersIdRoute
  '/admin/list/announcements': typeof ProtectedDashboardAdminAdminListAnnouncementsIndexRoute
  '/admin/list/assignments': typeof ProtectedDashboardAdminAdminListAssignmentsIndexRoute
  '/admin/list/classes': typeof ProtectedDashboardAdminAdminListClassesIndexRoute
  '/admin/list/events': typeof ProtectedDashboardAdminAdminListEventsIndexRoute
  '/admin/list/exams': typeof ProtectedDashboardAdminAdminListExamsIndexRoute
  '/admin/list/lessons': typeof ProtectedDashboardAdminAdminListLessonsIndexRoute
  '/admin/list/results': typeof ProtectedDashboardAdminAdminListResultsIndexRoute
  '/admin/list/students': typeof ProtectedDashboardAdminAdminListStudentsIndexRoute
  '/admin/list/subjects': typeof ProtectedDashboardAdminAdminListSubjectsIndexRoute
  '/admin/list/teachers': typeof ProtectedDashboardAdminAdminListTeachersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_protected/_dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/_dashboard/announcements': typeof ProtectedDashboardAnnouncementsLazyRoute
  '/_protected/_dashboard/admin': typeof ProtectedDashboardAdminRouteWithChildren
  '/_protected/_dashboard/admin/_admin': typeof ProtectedDashboardAdminAdminRouteWithChildren
  '/_protected/_dashboard/instructor': typeof ProtectedDashboardInstructorRouteWithChildren
  '/_protected/_dashboard/instructor/_instructor': typeof ProtectedDashboardInstructorInstructorRouteWithChildren
  '/_protected/_dashboard/student': typeof ProtectedDashboardStudentRouteWithChildren
  '/_protected/_dashboard/student/_student': typeof ProtectedDashboardStudentStudentRouteWithChildren
  '/_protected/_dashboard/instructor/_instructor/analytics': typeof ProtectedDashboardInstructorInstructorAnalyticsRoute
  '/_protected/_dashboard/instructor/_instructor/courses': typeof ProtectedDashboardInstructorInstructorCoursesRoute
  '/_protected/_dashboard/admin/_admin/': typeof ProtectedDashboardAdminAdminIndexRoute
  '/_protected/_dashboard/instructor/_instructor/': typeof ProtectedDashboardInstructorInstructorIndexRoute
  '/_protected/_dashboard/student/_student/': typeof ProtectedDashboardStudentStudentIndexRoute
  '/_protected/_dashboard/admin/_admin/list/students/$id': typeof ProtectedDashboardAdminAdminListStudentsIdRoute
  '/_protected/_dashboard/admin/_admin/list/teachers/$id': typeof ProtectedDashboardAdminAdminListTeachersIdRoute
  '/_protected/_dashboard/admin/_admin/list/announcements/': typeof ProtectedDashboardAdminAdminListAnnouncementsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/assignments/': typeof ProtectedDashboardAdminAdminListAssignmentsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/classes/': typeof ProtectedDashboardAdminAdminListClassesIndexRoute
  '/_protected/_dashboard/admin/_admin/list/events/': typeof ProtectedDashboardAdminAdminListEventsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/exams/': typeof ProtectedDashboardAdminAdminListExamsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/lessons/': typeof ProtectedDashboardAdminAdminListLessonsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/results/': typeof ProtectedDashboardAdminAdminListResultsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/students/': typeof ProtectedDashboardAdminAdminListStudentsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/subjects/': typeof ProtectedDashboardAdminAdminListSubjectsIndexRoute
  '/_protected/_dashboard/admin/_admin/list/teachers/': typeof ProtectedDashboardAdminAdminListTeachersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/register'
    | '/'
    | '/announcements'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/admin/'
    | '/instructor/'
    | '/student/'
    | '/admin/list/students/$id'
    | '/admin/list/teachers/$id'
    | '/admin/list/announcements'
    | '/admin/list/assignments'
    | '/admin/list/classes'
    | '/admin/list/events'
    | '/admin/list/exams'
    | '/admin/list/lessons'
    | '/admin/list/results'
    | '/admin/list/students'
    | '/admin/list/subjects'
    | '/admin/list/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | ''
    | '/'
    | '/announcements'
    | '/admin'
    | '/instructor'
    | '/student'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/admin/list/students/$id'
    | '/admin/list/teachers/$id'
    | '/admin/list/announcements'
    | '/admin/list/assignments'
    | '/admin/list/classes'
    | '/admin/list/events'
    | '/admin/list/exams'
    | '/admin/list/lessons'
    | '/admin/list/results'
    | '/admin/list/students'
    | '/admin/list/subjects'
    | '/admin/list/teachers'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/register'
    | '/_protected/_dashboard'
    | '/_protected/'
    | '/_protected/_dashboard/announcements'
    | '/_protected/_dashboard/admin'
    | '/_protected/_dashboard/admin/_admin'
    | '/_protected/_dashboard/instructor'
    | '/_protected/_dashboard/instructor/_instructor'
    | '/_protected/_dashboard/student'
    | '/_protected/_dashboard/student/_student'
    | '/_protected/_dashboard/instructor/_instructor/analytics'
    | '/_protected/_dashboard/instructor/_instructor/courses'
    | '/_protected/_dashboard/admin/_admin/'
    | '/_protected/_dashboard/instructor/_instructor/'
    | '/_protected/_dashboard/student/_student/'
    | '/_protected/_dashboard/admin/_admin/list/students/$id'
    | '/_protected/_dashboard/admin/_admin/list/teachers/$id'
    | '/_protected/_dashboard/admin/_admin/list/announcements/'
    | '/_protected/_dashboard/admin/_admin/list/assignments/'
    | '/_protected/_dashboard/admin/_admin/list/classes/'
    | '/_protected/_dashboard/admin/_admin/list/events/'
    | '/_protected/_dashboard/admin/_admin/list/exams/'
    | '/_protected/_dashboard/admin/_admin/list/lessons/'
    | '/_protected/_dashboard/admin/_admin/list/results/'
    | '/_protected/_dashboard/admin/_admin/list/students/'
    | '/_protected/_dashboard/admin/_admin/list/subjects/'
    | '/_protected/_dashboard/admin/_admin/list/teachers/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/login",
        "/register"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/_dashboard",
        "/_protected/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_protected/_dashboard": {
      "filePath": "_protected/_dashboard.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/_dashboard/announcements",
        "/_protected/_dashboard/admin",
        "/_protected/_dashboard/instructor",
        "/_protected/_dashboard/student"
      ]
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/_dashboard/announcements": {
      "filePath": "_protected/_dashboard/announcements.lazy.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/admin": {
      "filePath": "_protected/_dashboard/admin",
      "parent": "/_protected/_dashboard",
      "children": [
        "/_protected/_dashboard/admin/_admin"
      ]
    },
    "/_protected/_dashboard/admin/_admin": {
      "filePath": "_protected/_dashboard/admin/_admin.tsx",
      "parent": "/_protected/_dashboard/admin",
      "children": [
        "/_protected/_dashboard/admin/_admin/",
        "/_protected/_dashboard/admin/_admin/list/students/$id",
        "/_protected/_dashboard/admin/_admin/list/teachers/$id",
        "/_protected/_dashboard/admin/_admin/list/announcements/",
        "/_protected/_dashboard/admin/_admin/list/assignments/",
        "/_protected/_dashboard/admin/_admin/list/classes/",
        "/_protected/_dashboard/admin/_admin/list/events/",
        "/_protected/_dashboard/admin/_admin/list/exams/",
        "/_protected/_dashboard/admin/_admin/list/lessons/",
        "/_protected/_dashboard/admin/_admin/list/results/",
        "/_protected/_dashboard/admin/_admin/list/students/",
        "/_protected/_dashboard/admin/_admin/list/subjects/",
        "/_protected/_dashboard/admin/_admin/list/teachers/"
      ]
    },
    "/_protected/_dashboard/instructor": {
      "filePath": "_protected/_dashboard/instructor",
      "parent": "/_protected/_dashboard",
      "children": [
        "/_protected/_dashboard/instructor/_instructor"
      ]
    },
    "/_protected/_dashboard/instructor/_instructor": {
      "filePath": "_protected/_dashboard/instructor/_instructor.tsx",
      "parent": "/_protected/_dashboard/instructor",
      "children": [
        "/_protected/_dashboard/instructor/_instructor/analytics",
        "/_protected/_dashboard/instructor/_instructor/courses",
        "/_protected/_dashboard/instructor/_instructor/"
      ]
    },
    "/_protected/_dashboard/student": {
      "filePath": "_protected/_dashboard/student",
      "parent": "/_protected/_dashboard",
      "children": [
        "/_protected/_dashboard/student/_student"
      ]
    },
    "/_protected/_dashboard/student/_student": {
      "filePath": "_protected/_dashboard/student/_student.tsx",
      "parent": "/_protected/_dashboard/student",
      "children": [
        "/_protected/_dashboard/student/_student/"
      ]
    },
    "/_protected/_dashboard/instructor/_instructor/analytics": {
      "filePath": "_protected/_dashboard/instructor/_instructor/analytics.tsx",
      "parent": "/_protected/_dashboard/instructor/_instructor"
    },
    "/_protected/_dashboard/instructor/_instructor/courses": {
      "filePath": "_protected/_dashboard/instructor/_instructor/courses.tsx",
      "parent": "/_protected/_dashboard/instructor/_instructor"
    },
    "/_protected/_dashboard/admin/_admin/": {
      "filePath": "_protected/_dashboard/admin/_admin/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/instructor/_instructor/": {
      "filePath": "_protected/_dashboard/instructor/_instructor/index.tsx",
      "parent": "/_protected/_dashboard/instructor/_instructor"
    },
    "/_protected/_dashboard/student/_student/": {
      "filePath": "_protected/_dashboard/student/_student/index.tsx",
      "parent": "/_protected/_dashboard/student/_student"
    },
    "/_protected/_dashboard/admin/_admin/list/students/$id": {
      "filePath": "_protected/_dashboard/admin/_admin/list/students/$id.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/teachers/$id": {
      "filePath": "_protected/_dashboard/admin/_admin/list/teachers/$id.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/announcements/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/announcements/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/assignments/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/assignments/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/classes/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/classes/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/events/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/events/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/exams/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/exams/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/lessons/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/lessons/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/results/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/results/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/students/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/students/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/subjects/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/subjects/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    },
    "/_protected/_dashboard/admin/_admin/list/teachers/": {
      "filePath": "_protected/_dashboard/admin/_admin/list/teachers/index.tsx",
      "parent": "/_protected/_dashboard/admin/_admin"
    }
  }
}
ROUTE_MANIFEST_END */
